# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/arima_learn',
                'doc_host': 'https://barakdiker.github.io',
                'git_url': 'https://github.com/barakdiker/arima_learn',
                'lib_path': 'arima_learn'},
  'syms': {'arima_learn.core': {'arima_learn.core.foo': ('core.html#foo', 'arima_learn/core.py')}}}
